pimcore:
    objects:
        custom_layouts:
            definitions:
                customLayout:
                    id: customLayout
                    name: customLayout
                    description: ''
                    creationDate: 1698926650
                    modificationDate: 1699627846
                    userOwner: 2
                    classId: '2'
                    layoutDefinitions:
                        name: pimcore_root
                        type: null
                        region: null
                        title: null
                        width: 0
                        height: 0
                        collapsible: false
                        collapsed: false
                        bodyStyle: null
                        datatype: layout
                        children:
                            -
                                name: basic
                                type: null
                                region: null
                                title: Basic
                                width: ''
                                height: ''
                                collapsible: false
                                collapsed: false
                                bodyStyle: ''
                                datatype: layout
                                children:
                                    -
                                        name: name
                                        title: Name
                                        tooltip: ''
                                        mandatory: true
                                        noteditable: false
                                        index: false
                                        locked: false
                                        style: ''
                                        permissions: null
                                        fieldtype: input
                                        relationType: false
                                        invisible: false
                                        visibleGridView: false
                                        visibleSearch: false
                                        defaultValue: null
                                        columnLength: 190
                                        regex: ''
                                        regexFlags: {  }
                                        unique: false
                                        showCharCount: false
                                        width: ''
                                        defaultValueGenerator: ''
                                        datatype: data
                                    -
                                        name: description
                                        title: Description
                                        tooltip: ''
                                        mandatory: false
                                        noteditable: false
                                        index: false
                                        locked: false
                                        style: ''
                                        permissions: null
                                        fieldtype: textarea
                                        relationType: false
                                        invisible: false
                                        visibleGridView: false
                                        visibleSearch: false
                                        maxLength: null
                                        showCharCount: false
                                        excludeFromSearchIndex: false
                                        height: ''
                                        width: ''
                                        datatype: data
                                    -
                                        name: stockAvailability
                                        title: 'Stock Availability'
                                        tooltip: ''
                                        mandatory: false
                                        noteditable: false
                                        index: false
                                        locked: false
                                        style: ''
                                        permissions: null
                                        fieldtype: booleanSelect
                                        relationType: false
                                        invisible: false
                                        visibleGridView: false
                                        visibleSearch: false
                                        yesLabel: 'yes'
                                        noLabel: 'no'
                                        emptyLabel: empty
                                        options:
                                            -
                                                key: empty
                                                value: 0
                                            -
                                                key: 'yes'
                                                value: 1
                                            -
                                                key: 'no'
                                                value: -1
                                        width: ''
                                        datatype: data
                                locked: false
                                fieldtype: panel
                                layout: null
                                border: false
                                icon: ''
                                labelWidth: 100
                                labelAlign: left
                        locked: false
                        fieldtype: panel
                        layout: null
                        border: false
                        icon: null
                        labelWidth: 100
                        labelAlign: left
                    default: 0
