pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    galleryCarousel:
                        items:
                            -
                                method: resize
                                arguments:
                                    width: 1280
                                    height: 620
                        medias: {  }
                        name: galleryCarousel
                        description: ''
                        group: Areas
                        format: ORIGINAL
                        quality: 100
                        highResolution: 1.0
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1699714100
                        creationDate: 1699704482
                        preserveAnimation: false
