pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    productDetails:
                        items:
                            -
                                method: resize
                                arguments:
                                    width: 430
                                    height: 600
                        medias: {  }
                        name: productDetails
                        description: ''
                        group: ''
                        format: SOURCE
                        quality: 85
                        highResolution: null
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1700459309
                        creationDate: 1700459295
                        preserveAnimation: false
