pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    product_card:
                        items:
                            -
                                method: contain
                                arguments:
                                    width: 150
                                    height: 150
                                    forceResize: true
                        medias: {  }
                        name: product_card
                        description: 'for product card'
                        group: ''
                        format: SOURCE
                        quality: 85
                        highResolution: null
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1699681751
                        creationDate: 1699681703
                        preserveAnimation: false
