parameters:
    secret: azluFrhehN8EkmiAbue8JdbDc9s+GF+PTdIhc4ycKqI=
    pimcore_asset_path: "/public/var/assets"
    notification_sender: "siwachs128@gmail.com"
    notification_receiver: "siwachs128@gmail.com"

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    App\Controller\:
        resource: "../src/Controller"
        public: true
        tags: ["controller.service_arguments"]

    calculate_price:
        class: App\Controller\ActualPriceCalculator

    # Twig Ext
    App\Twig\Extension\UniqidExtension:
        tags: ["twig.extension"]

    # Event Listeners
    App\EventListener\ObjectListener:
        tags:
            - {
                  name: kernel.event_listener,
                  event: pimcore.dataobject.preUpdate,
                  method: onObjectPreUpdate,
              }
            - {
                  name: kernel.event_listener,
                  event: pimcore.dataobject.postUpdate,
                  method: onObjectPostUpdate,
              }

    # Workflow Listeners
    App\EventListener\WorkflowListener:
        tags:
            - {
                  name: kernel.event_listener,
                  event: workflow.product_workflow.transition.start_enrichment,
                  method: onTransitionToEnrichment,
              }
            - {
                  name: kernel.event_listener,
                  event: workflow.product_workflow.transition.finish_enrichment,
                  method: onTransitionToTechnicalities,
              }
