pimcore:
    workflows:
        workflow:
            label: "Product Workflow"
            type: "state_machine"
            supports:
                - 'Pimcore\Model\DataObject\Product'
            places:
                new:
                    label: "New product"
                    color: "#377ea9"
                    permissions:
                        - objectLayout: customLayout
                rejected:
                    label: "Rejected product"
                    color: "#28a013"
                update_content:
                    label: "Update Content"
                    title: "Updating content step"
                    color: "#d9ef36"
                    permissions:
                        - objectLayout: customLayout
                content_prepared:
                    label: "Content Prepared"
                    title: "Content ready to publish"
                    color: "#28a013"
                accepted:
                    label: "Accepted product"
                    color: "#28a013"
            transitions:
                reject_product:
                    from: new
                    to: rejected
                    options:
                        label: "Reject the product"
                        notes:
                            commentEnabled: true
                            commentRequired: true
                start_processing:
                    from: new
                    to: update_content
                    options:
                        label: "Start processing the product"
                content_ready:
                    from: update_content
                    to: content_prepared
                    options:
                        label: "Content is ready to publish"
                publish:
                    from: content_prepared
                    to: accepted
                    guard: "is_fully_authenticated() and is_granted('ROLE_PIMCORE_ADMIN')"
                    options:
                        label: "Publish the product"
                        notes:
                            commentEnabled: true
                            commentRequired: true
