pimcore:
    workflows:
        product_workflow:
            label: "Product Workflow"
            type: "state_machine"
            supports:
                - 'Pimcore\Model\DataObject\Product'
            places:
                new:
                    label: "Start: Adding Basic Information"
                    color: "#377ea9"
                    permissions:
                        - objectLayout: BasicInformation
                enrich_product:
                    label: "Adding Data Enrichment"
                    title: "Commerce Team"
                    color: "#d9ef36"
                    permissions:
                        - objectLayout: CommerceTeam
                add_technicalities:
                    label: "Adding Technical Details"
                    title: "Technician Team"
                    color: "#28a013"
                    permissions:
                        - objectLayout: TechnicianTeam
                review:
                    label: "Review Process"
                    color: "#ffa500"
                    permissions:
                        - objectLayout: ReviewerLayout
                accepted:
                    label: "Accepted product"
                    color: "#28a013"
                rejected:
                    label: "Rejected product"
                    color: "#d9534f"
                exited:
                    label: "Exited workflow"
            transitions:
                start_enrichment:
                    from: new
                    to: enrich_product
                    guard: "is_fully_authenticated() and (is_granted('ROLE_PIMCORE_ADMIN') or  is_granted('ROLE_OPERATOR'))"
                    options:
                        label: "Start adding data enrichment"
                        notes:
                            commentEnabled: true
                            commentRequired: true
                        notificationSettings:
                            - notifyUsers: ["admin"]
                              notifyRoles: ["commerce", "review"]
                              channelType:
                                  - pimcore_notification
                finish_enrichment:
                    from: enrich_product
                    to: add_technicalities
                    guard: "is_fully_authenticated() and (is_granted('ROLE_PIMCORE_ADMIN') or  is_granted('ROLE_COMMERCE'))"
                    options:
                        label: "Finish data enrichment"
                        notes:
                            commentEnabled: true
                            commentRequired: true
                        notificationSettings:
                            - notifyUsers: ["admin"]
                              notifyRoles: ["technician", "review"]
                              channelType:
                                  - pimcore_notification
                finish_technicalities:
                    from: add_technicalities
                    to: review
                    guard: "is_fully_authenticated() and (is_granted('ROLE_PIMCORE_ADMIN') or  is_granted('ROLE_TECHNICIAN'))"
                    options:
                        label: "Finish adding technical details"
                        notes:
                            commentEnabled: true
                            commentRequired: true
                        notificationSettings:
                            - notifyUsers: ["admin"]
                              notifyRoles: ["review"]
                              channelType:
                                  - pimcore_notification
                accept_product:
                    from: review
                    to: accepted
                    guard: "is_fully_authenticated() and (is_granted('ROLE_PIMCORE_ADMIN') or  is_granted('ROLE_REVIEW'))"
                    options:
                        label: "Accept product"
                        notes:
                            commentEnabled: true
                            commentRequired: true
                        notificationSettings:
                            - notifyUsers: ["admin"]
                              channelType:
                                  - pimcore_notification
                reject_enrichment:
                    from: review
                    to: enrich_product
                    guard: "is_fully_authenticated() and (is_granted('ROLE_PIMCORE_ADMIN') or  is_granted('ROLE_REVIEW'))"
                    options:
                        label: "Reject enrichment"
                        notes:
                            commentEnabled: true
                            commentRequired: true
                reject_technicalities:
                    from: review
                    to: add_technicalities
                    guard: "is_fully_authenticated() and (is_granted('ROLE_PIMCORE_ADMIN') or  is_granted('ROLE_REVIEW'))"
                    options:
                        label: "Reject technicalities"
                        notes:
                            commentEnabled: true
                            commentRequired: true
                reject_product:
                    from: review
                    to: rejected
                    guard: "is_fully_authenticated() and (is_granted('ROLE_PIMCORE_ADMIN') or  is_granted('ROLE_REVIEW'))"
                    options:
                        label: "Reject the entire product"
                        notes:
                            commentEnabled: true
                            commentRequired: true
                exit_workflow:
                    from:
                        - new
                        - enrich_product
                        - add_technicalities
                        - review
                    to: exited
                    guard: "is_fully_authenticated() and is_granted('ROLE_PIMCORE_ADMIN')"
                    options:
                        label: "Exit workflow"
                restart_workflow:
                    from: exited
                    to: new
                    guard: "is_fully_authenticated() and is_granted('ROLE_PIMCORE_ADMIN')"
                    options:
                        label: "Restart workflow"
