pimcore:
    workflows:
        product_workflow:
            label: "Product Workflow"
            type: "state_machine"
            supports:
                - 'Pimcore\Model\DataObject\Product'
            places:
                new:
                    label: "Start: Adding Basic Information"
                    color: "#377ea9"
                    permissions:
                        - objectLayout: BasicInformation
                enrich_product:
                    label: "Adding Data Enrichment"
                    title: "Commerce Team"
                    color: "#d9ef36"
                    permissions:
                        - objectLayout: CommerceTeam
                add_technicalities:
                    label: "Adding Technical Details"
                    title: "Technician Team"
                    color: "#28a013"
                    permissions:
                        - objectLayout: TechnicianTeam
                review:
                    label: "Review Process"
                    color: "#ffa500"
                    permissions:
                        - objectLayout: ReviewerLayout
                accepted:
                    label: "Accepted product"
                    color: "#28a013"
                rejected:
                    label: "Rejected product"
                    color: "#d9534f"
                exited:
                    label: "Exited workflow"
                    color: "#808080"
            transitions:
                start_enrichment:
                    from: new
                    to: enrich_product
                    options:
                        label: "Start adding data enrichment"
                        notes:
                            commentEnabled: true
                            commentRequired: true
                finish_enrichment:
                    from: enrich_product
                    to: add_technicalities
                    options:
                        label: "Finish data enrichment"
                        notes:
                            commentEnabled: true
                            commentRequired: true
                finish_technicalities:
                    from: add_technicalities
                    to: review
                    options:
                        label: "Finish adding technical details"
                        notes:
                            commentEnabled: true
                            commentRequired: true
                accept_product:
                    from: review
                    to: accepted
                    options:
                        label: "Accept product"
                        notes:
                            commentEnabled: true
                            commentRequired: true
                reject_enrichment:
                    from: enrich_product
                    to: new
                    options:
                        label: "Reject enrichment and go back to start"
                        notes:
                            commentEnabled: true
                            commentRequired: true
                reject_technicalities:
                    from: add_technicalities
                    to: enrich_product
                    options:
                        label: "Reject technicalities and go back to data enrichment"
                        notes:
                            commentEnabled: true
                            commentRequired: true
                reject_review:
                    from: review
                    to: add_technicalities
                    options:
                        label: "Reject review and go back to adding technical details"
                        notes:
                            commentEnabled: true
                            commentRequired: true
                reject_accepted:
                    from: accepted
                    to: review
                    options:
                        label: "Reject accepted product and go back to review"
                        notes:
                            commentEnabled: true
                            commentRequired: true
                exit_workflow:
                    from:
                        - new
                        - enrich_product
                        - add_technicalities
                        - review
                    to: exited
                    guard: "is_fully_authenticated() and is_granted('ROLE_PIMCORE_ADMIN')"
                    options:
                        label: "Exit workflow"
                restart_workflow:
                    from: exited
                    to: new
                    guard: "is_fully_authenticated() and is_granted('ROLE_PIMCORE_ADMIN')"
                    options:
                        label: "Restart workflow"
