pimcore_custom_reports:
    definitions:
        ProductCount:
            name: ProductCount
            sql: ''
            dataSourceConfig:
                -
                    sql: "object_Category.key AS 'Category', COUNT(object_Product.id) AS 'Product Count'"
                    from: "object_Category LEFT JOIN object_Product ON object_Category.id = REPLACE(object_Product.category,',','') OR object_Category.id = REPLACE(object_Product.subCategory, ',', '')"
                    where: ''
                    groupby: 'GROUP BY object_Category.key ORDER BY COUNT(object_Product.id) DESC'
                    type: sql
            columnConfiguration:
                -
                    name: Category
                    display: true
                    export: true
                    order: true
                    width: ''
                    label: ''
                    id: extModel243-3
                -
                    name: 'Product Count'
                    display: true
                    export: true
                    order: true
                    width: ''
                    label: ''
                    id: extModel243-4
            niceName: ''
            group: ''
            groupIconClass: ''
            iconClass: ''
            menuShortcut: true
            reportClass: ''
            chartType: pie
            pieColumn: 'Product Count'
            pieLabelColumn: Category
            xAxis: null
            yAxis: {  }
            modificationDate: 1702374010
            creationDate: 1701410589
            shareGlobally: true
            sharedUserNames: {  }
            sharedRoleNames: {  }
