pimcore_custom_reports:
    definitions:
        WorkflowReportPie:
            name: WorkflowReportPie
            sql: ''
            dataSourceConfig:
                -
                    sql: "element_workflow_state.place as 'Currently In State',count(*) as number"
                    from: 'element_workflow_state JOIN objects ON element_workflow_state.cid = objects.id'
                    where: ''
                    groupby: 'GROUP BY element_workflow_state.place'
                    type: sql
            columnConfiguration:
                -
                    name: 'Currently In State'
                    display: true
                    export: true
                    order: true
                    width: ''
                    label: ''
                    id: extModel314-1
                -
                    name: number
                    display: true
                    export: true
                    order: true
                    width: ''
                    label: ''
                    id: extModel314-2
            niceName: ''
            group: ''
            groupIconClass: ''
            iconClass: ''
            menuShortcut: true
            reportClass: ''
            chartType: pie
            pieColumn: number
            pieLabelColumn: 'Currently In State'
            xAxis: null
            yAxis: {  }
            modificationDate: 1702013682
            creationDate: 1702013571
            shareGlobally: true
            sharedUserNames: {  }
            sharedRoleNames: {  }
